/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AcompanhamentoRouteImport } from './routes/acompanhamento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreinoIdRouteImport } from './routes/treino.$id'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AlunosAlunoIdRouteImport } from './routes/alunos.$alunoId'

const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoRoute = AcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoIdRoute = TreinoIdRouteImport.update({
  id: '/treino/$id',
  path: '/treino/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosAlunoIdRoute = AlunosAlunoIdRouteImport.update({
  id: '/$alunoId',
  path: '/$alunoId',
  getParentRoute: () => AlunosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/clientes': typeof ClientesRoute
  '/dieta': typeof DietaRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/treinos': typeof TreinosRoute
  '/alunos/$alunoId': typeof AlunosAlunoIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/treino/$id': typeof TreinoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/clientes': typeof ClientesRoute
  '/dieta': typeof DietaRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/treinos': typeof TreinosRoute
  '/alunos/$alunoId': typeof AlunosAlunoIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/treino/$id': typeof TreinoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/clientes': typeof ClientesRoute
  '/dieta': typeof DietaRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/treinos': typeof TreinosRoute
  '/alunos/$alunoId': typeof AlunosAlunoIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/treino/$id': typeof TreinoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhamento'
    | '/agenda'
    | '/alunos'
    | '/auth'
    | '/avaliacoes'
    | '/clientes'
    | '/dieta'
    | '/feed'
    | '/forgot-password'
    | '/notificacoes'
    | '/perfil'
    | '/reset-password'
    | '/treinos'
    | '/alunos/$alunoId'
    | '/convite/$token'
    | '/treino/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhamento'
    | '/agenda'
    | '/alunos'
    | '/auth'
    | '/avaliacoes'
    | '/clientes'
    | '/dieta'
    | '/feed'
    | '/forgot-password'
    | '/notificacoes'
    | '/perfil'
    | '/reset-password'
    | '/treinos'
    | '/alunos/$alunoId'
    | '/convite/$token'
    | '/treino/$id'
  id:
    | '__root__'
    | '/'
    | '/acompanhamento'
    | '/agenda'
    | '/alunos'
    | '/auth'
    | '/avaliacoes'
    | '/clientes'
    | '/dieta'
    | '/feed'
    | '/forgot-password'
    | '/notificacoes'
    | '/perfil'
    | '/reset-password'
    | '/treinos'
    | '/alunos/$alunoId'
    | '/convite/$token'
    | '/treino/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanhamentoRoute: typeof AcompanhamentoRoute
  AgendaRoute: typeof AgendaRoute
  AlunosRoute: typeof AlunosRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  ClientesRoute: typeof ClientesRoute
  DietaRoute: typeof DietaRoute
  FeedRoute: typeof FeedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TreinosRoute: typeof TreinosRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  TreinoIdRoute: typeof TreinoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento': {
      id: '/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/$id': {
      id: '/treino/$id'
      path: '/treino/$id'
      fullPath: '/treino/$id'
      preLoaderRoute: typeof TreinoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/$alunoId': {
      id: '/alunos/$alunoId'
      path: '/$alunoId'
      fullPath: '/alunos/$alunoId'
      preLoaderRoute: typeof AlunosAlunoIdRouteImport
      parentRoute: typeof AlunosRoute
    }
  }
}

interface AlunosRouteChildren {
  AlunosAlunoIdRoute: typeof AlunosAlunoIdRoute
}

const AlunosRouteChildren: AlunosRouteChildren = {
  AlunosAlunoIdRoute: AlunosAlunoIdRoute,
}

const AlunosRouteWithChildren =
  AlunosRoute._addFileChildren(AlunosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanhamentoRoute: AcompanhamentoRoute,
  AgendaRoute: AgendaRoute,
  AlunosRoute: AlunosRouteWithChildren,
  AuthRoute: AuthRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  ClientesRoute: ClientesRoute,
  DietaRoute: DietaRoute,
  FeedRoute: FeedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TreinosRoute: TreinosRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  TreinoIdRoute: TreinoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
